apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service-deployment
  labels:
    app: {{ .Values.labels.deployment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
      - name: go-service
        image: registry.hub.docker.com/galins/go-service:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /v1/data
            port: 8080
          periodSeconds: 300
          failureThreshold: 3


---



apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.svc }}
spec:
  type: NodePort
  selector:
    app: go-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
